dist: trusty
language: erlang
notifications:
  email: false
otp_release:
  - 23.0.2
  - 22.3.4
  - 22.2.8
  - 22.1.8.1
  - 22.0.7
  - 21.3.8
  - 21.1.4
  - 20.3.8
  - 19.3.6
  - 19.2
  - 18.3
  - 17.5
script: rebar get-deps && rebar compile && rebar xref && rebar eunit
